name: blitz_score
description: It is an individual project developed to learn and enhance programming skills using Flutter. Designed to be user-friendly and visually appealing, it's a fun way to engage with friends while primarily playing Dutch Blitz. The main goal of this app is to tally points by adding or subtracting the desired number from the score with minimal screen touches.

version: 1.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  provider: ^6.0.3
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  path: ^1.8.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_icons:
  android: 'icon'
  ios: true
  image_path: 'images/icon.png'

flutter:
  generate: true
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
