name: blitz_score
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  provider: ^6.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_launcher_icons: '^0.9.2'
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: 'icon'
  ios: true
  image_path: 'images/icon.png'

flutter:
  generate: true
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
